//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsaCheck.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsaCheck.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;qwe&quot;: &quot;asd&quot; }.
        /// </summary>
        internal static string message_json {
            get {
                return ResourceManager.GetString("message.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PRIVATE KEY-----MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKOY67BjmDLjbc/kIaqemRMQnDmQd+lRdy/BgjwzJr32Hf45OFC9sPK6807gWXtltanOwiKA7sGxxYUl40Es/wE37BckideGlu4MqIQYTaJjdu2OK78KxFaC+1kRZkNuoSBzi2GX9V84IXiwZG/0VatFTtONOdHInEriMPSIxXj3AgMBAAECgYBjzEaCzM6sxHZZqpYrCiLhMXHL3+h2aV7mwAodhSquGTSEwA0tm/oUqJ0CUfPkRdCDLQDaoYKEoFiY99rhCHzqHH57KoeD4SQlyfUim1f6dzhVneZedYnIhZHJ0B+jTcumeO49ZzaezqyLxuoHiygBCgUIuaFbtgCrUuljtUH7+QJBANTKXAz6svG8V9n81gGUlFmcToFiBmqc884RQ45g0NtbrIkKJdvJpz7kF2brEurkdJZ2Fj0pvz7WLkE+H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string privateKey {
            get {
                return ResourceManager.GetString("privateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCjmOuwY5gy423P5CGqnpkTEJw5kHfpUXcvwYI8Mya99h3+OThQvbDyuvNO4Fl7ZbWpzsIigO7BscWFJeNBLP8BN+wXJInXhpbuDKiEGE2iY3btjiu/CsRWgvtZEWZDbqEgc4thl/VfOCF4sGRv9FWrRU7TjTnRyJxK4jD0iMV49wIDAQAB-----END PUBLIC KEY-----.
        /// </summary>
        internal static string publicKey {
            get {
                return ResourceManager.GetString("publicKey", resourceCulture);
            }
        }
    }
}
